### ISSUE TITLE
Issue to compile Node Monitoring 

### ISSUE THREAD

**Issue by HW-Whalecomm** [SiliconLabs/wisun_applications#1]
I created the project acoording to the dodumenation but during the compile process there is a problem in "app.c" Description	Resource	Path	Location	Type
fatal error: app_tcp_server.h: No such file or directory	app.c	/wisun_node_monitoring	line 67	C/C++ Problem

I compile to zG28 Explorer Kit the uC is EFR32ZG28

**Comment by MarcDorval** [comment]
It should work now, I uploaded a correction to the version check yesterday, so you were just unlucky to clone at the last minute before the correction. Sorry about that.
The change related to this error is that the UDP and TCP server code wasn't listed in the .slcp file. It now is.

**Comment by MarcDorval** [comment]
Please update the external repository in Simplicity Studio then re-generate your project.
Close this issue when it works.

**Comment by HW-Whalecomm** [comment]
Thanks for the update, it works well now
