### ISSUE TITLE
Compile error 

### ISSUE THREAD

**Issue by jhoonf19** [SiliconLabs/wisun_applications#2]
I've updated to the new version of the project and it gives an error because it can't find the sl_memory_manager.h library in app_rtt_traces. I tried to add it to the .slcp file, but was unsuccessful.

**Comment by MarcDorval** [comment]
This was due to the introduction of the memory manager. It has been solved adding version checking in https://github.com/SiliconLabs/wisun_applications/blob/main/wisun_node_monitoring/app_rtt_traces.c#L43

**Comment by MarcDorval** [comment]
Closing as it is now working
